### ISSUE TITLE
General Help or Diagnosis

### ISSUE THREAD

**Issue by quatre432** [r-cute/rcute-cozmars-server#32]
I am generally new at python, but im trying to get cozmars working 
the html doesn't seem to do anything doing a basic connection from my pc doesn't seem to change anything 
my screen is just showing cozmars 37d0 on boot up and doesn't change

I'm not sure if i don't have things plugged in right or maybe something is wrong on my install on pi can anyone give me any tips for diagnosis 

Another a little investigation on Robot connection through python or html this error is returned

[2021-10-26 07:12:15 -0900] [877] [INFO] connection open
[2021-10-26 07:12:25 -0900] [877] [ERROR] Exception occurred while handling uri: 'ws://192.168.0.181/rpc'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 891, in _websocket_handler
    await fut
  File "/usr/local/lib/python3.7/dist-packages/rcute_cozmars_server/__main__.py", line 83, in rpc
    await RPCServer(ws, cozmars_rpc_server).run()
  File "/usr/local/lib/python3.7/dist-packages/wsmprpc/server.py", line 27, in run
    async for data in self.ws:
TypeError: 'async for' requires an object with __aiter__ method, got WebsocketImplProtocol

**Comment by hyansuper** [comment]
Your error has to do with [wsmprpc](https://github.com/hyansuper/wsmprpc/)
On your pi, disable cozmars server by `sudo systemctl disable cozmars.service` then you run the script https://github.com/hyansuper/wsmprpc/blob/master/examples/server_test_sanic.py
and then from your PC run https://github.com/hyansuper/wsmprpc/blob/master/examples/client_test.py, see if any error occur from your pi or PC
remember to change the address at https://github.com/hyansuper/wsmprpc/blob/master/examples/client_test.py#L5 to your pi's address

**Comment by hyansuper** [comment]
> my screen is just showing cozmars 37d0 on boot up and doesn't change

that's not an error, 37d0 is your robot's serial code. the robot does not do any thing unless you control it

**Comment by quatre432** [comment]
Thanks for the response i ran the script on the pi and tried both your script and the client test on the client test i recieved this response on the pi 

[2021-11-06 14:37:06 -0500] [1379] [INFO] connection open
[2021-11-06 14:37:06 -0500] [1379] [ERROR] Exception occurred while handling uri: 'ws://192.168.0.181:8000/'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 891, in _websocket_handler
    await fut
  File "server_test_sanic.py", line 48, in home
    await RPCServer(ws, SimpleHandler()).run()
  File "/usr/local/lib/python3.7/dist-packages/wsmprpc/server.py", line 27, in run
    async for data in self.ws:
TypeError: 'async for' requires an object with __aiter__ method, got WebsocketImplProtocol

which is more or less what i got before , i have uninstalled websockets and reinstalled them, its on version 10.0 if it helps

**Comment by hyansuper** [comment]
Try the very basic server - client example from https://websockets.readthedocs.io/en/stable/
If it produce the same error, you can seek help at https://github.com/aaugustin/websockets

**Comment by quatre432** [comment]
Thank I Have tried there basic server and client and they work successfully without error

**Comment by hyansuper** [comment]
I can't reproduce the error, I suggest you clone the latest code on pi
```
git clone https://github.com/r-cute/rcute-cozmars-server.git
cd rcute-cozmars-server
sudo python3 -m pip install -e .
sudo systemctl restart cozmars.service
```
if the same error shows again, try edit you file /usr/local/lib/python3.7/dist-packages/wsmprpc/server.py and change [line27](https://github.com/hyansuper/wsmprpc/blob/master/wsmprpc/server.py#L27) into the following 2 lines
````
            while True:
                data = await self.ws.recv()
````

**Comment by quatre432** [comment]
Thanks changing that code seems to make it respond properly now, screen and servos work but not motors or sound im going to make sure they are on the correct pins though

**Comment by sam-got** [comment]
Help me!!!
I have this error... 

Main  2025-03-23 17:22:48 +0000 WARNING:  Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
Sanic app name '__mp_main__' not found.
App instantiation must occur outside if __name__ == '__main__' block or by using an AppLoader.
See https://sanic.dev/en/guide/deployment/app-loader.html for more details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sanic/app.py", line 2221, in get_app
    return cls._app_registry[name]
           ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sanic/app.py", line 2221, in get_app
    return cls._app_registry[name]
           ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '__mp_main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sanic/worker/serve.py", line 56, in worker_serve
    app = app_loader.load()
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sanic/worker/loader.py", line 75, in load
    return self.factory()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sanic/app.py", line 2224, in get_app
    return cls.get_app("__mp_main__", force_create=force_create)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sanic/app.py", line 2227, in get_app
    raise SanicException(
sanic.exceptions.SanicException: Sanic app name '__mp_main__' not found.
App instantiation must occur outside if __name__ == '__main__' block or by using an AppLoader.
See https://sanic.dev/en/guide/deployment/app-loader.html for more details.
Main  2025-03-23 17:22:55 +0000 ERROR:    Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
Main  2025-03-23 17:22:55 +0000 INFO:     Killing Sanic-Server-0-0 [2755]
Killed

**Comment by obiwan51** [comment]
Downgrade your python. This only works on python 3.7 an 3.8. After you downgrade install the server again

**Comment by sam-got** [comment]
> Downgrade your python. This only works on python 3.7 an 3.8. After you downgrade install the server again

I reinstall all with python 3.8 and have this console message...

sudo python -m rcute_cozmars_server
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/rcute_cozmars_server/__main__.py", line 2, in <module>
    import sanic
  File "/usr/local/lib/python3.8/site-packages/sanic/__init__.py", line 6, in <module>
    from sanic.app import Sanic
  File "/usr/local/lib/python3.8/site-packages/sanic/app.py", line 50, in <module>
    from sanic.application.state import ApplicationState, ServerStage
  File "/usr/local/lib/python3.8/site-packages/sanic/application/state.py", line 12, in <module>
    from sanic.log import VerbosityFilter, logger
  File "/usr/local/lib/python3.8/site-packages/sanic/log.py", line 1, in <module>
    from sanic.logging.color import Colors
  File "/usr/local/lib/python3.8/site-packages/sanic/logging/color.py", line 8, in <module>
    from sanic.helpers import is_atty
  File "/usr/local/lib/python3.8/site-packages/sanic/helpers.py", line 21, in <module>
    STATUS_CODES: dict[int, bytes] = {
TypeError: 'type' object is not subscriptable
